package eu.midnightdust.motschen.modernarch;

import eu.midnightdust.motschen.modernarch.block.*;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder;
import net.minecraft.block.Block;
import net.minecraft.item.*;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class ModernArchMain implements ModInitializer {
    public static final String MOD_ID = "modernarch_r_mod";

    public static final ItemGroup ModernArchGroup = FabricItemGroupBuilder.build(new Identifier(MOD_ID, "tabmdnr"), () -> new ItemStack(ModernArchMain.PlantVase));
    public static Block HandrailWallR = new RotatableBlock();
    public static Block KitchenSink2 = new RotatableBlock();
    public static Block TV = new RotatableBlock();
    public static Block StairStepsHandrailR = new RotatableBlock();
    public static Block KitchenSink3 = new RotatableBlock();
    public static Block WoodStructureCircle = new RotatableBlock();
    public static Block PlantVase = new RotatableBlock();
    public static Block HandrailL = new RotatableBlock();
    public static Block StairStepsHandrailL = new RotatableBlock();
    public static Block HandrailWallL = new RotatableBlock();
    public static Block BlckChair = new RotatableBlock();
    public static Block HandrailR = new RotatableBlock();
    public static Block Mirror = new RotatableBlock();
    public static Block KitchenSink = new RotatableBlock();
    public static Block Sofa = new RotatableBlock();
    public static Block Armchair = new RotatableBlock();
    public static Block Sink = new RotatableBlock();
    public static Block Bed = new RotatableBlock();
    public static Block Handrail = new RotatableBlock();
    public static Block WhiteRoundCarpet = new RotatableBlock();
    public static Block StairsWall = new RotatableBlock();
    public static Block Fridge = new RotatableBlock();
    public static Block StairStepsHandrailWallL = new RotatableBlock();
    public static Block Wardrobe = new RotatableBlock();
    public static Block Chair1 = new RotatableBlock();
    public static Block Curtain = new RotatableBlock();
    public static Block Notebook = new RotatableBlock();
    public static Block StairStepsHandrailWallR = new RotatableBlock();
    public static Block StairsWallR = new RotatableBlock();
    public static Block Table1 = new RotatableBlock();
    public static Block Table2 = new RotatableBlock();
    public static Block StairsWallL = new RotatableBlock();
    public static Block Stairs = new RotatableBlock();
    public static Block CenterTable = new RotatableBlock();
    public static Block WoodStructure = new RotatableBlock();
    public static Block HandrailWall = new RotatableBlock();
    public static Block BlackRoundCarpet = new RotatableBlock();
    public static Block WhiteRoundTable = new RotatableBlock();
    public static Block StairStepsMid = new RotatableBlock();
    public static Block CeilingLamp = new CeilingLamp();

    @Override
    public void onInitialize() {
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"handrail_wall_r"), HandrailWallR);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"handrail_wall_r"), new BlockItem(HandrailWallR, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"kitchensink2"), KitchenSink2);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"kitchensink2"), new BlockItem(KitchenSink2, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"tv"), TV);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"tv"), new BlockItem(TV, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"stair_steps_handrail_r"), StairStepsHandrailR);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"stair_steps_handrail_r"), new BlockItem(StairStepsHandrailR, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"kitchensink3"), KitchenSink3);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"kitchensink3"), new BlockItem(KitchenSink3, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"woodstructurecircle"), WoodStructureCircle);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"woodstructurecircle"), new BlockItem(WoodStructureCircle, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"plantvase"), PlantVase);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"plantvase"), new BlockItem(PlantVase, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"handraill"), HandrailL);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"handraill"), new BlockItem(HandrailL, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"stairstepshandraill"), StairStepsHandrailL);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"stairstepshandraill"), new BlockItem(StairStepsHandrailL, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"handrail_wall_l"), HandrailWallL);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"handrail_wall_l"), new BlockItem(HandrailWallL, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"blckchair"), BlckChair);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"blckchair"), new BlockItem(BlckChair, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"handrail_r"), HandrailR);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"handrail_r"), new BlockItem(HandrailR, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"mirror"), Mirror);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"mirror"), new BlockItem(Mirror, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"kitchensink"), KitchenSink);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"kitchensink"), new BlockItem(KitchenSink, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"sofa"), Sofa);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"sofa"), new BlockItem(Sofa, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"armchair"), Armchair);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"armchair"), new BlockItem(Armchair, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"sink"), Sink);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"sink"), new BlockItem(Sink, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"bed"), Bed);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"bed"), new BlockItem(Bed, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"handrail"), Handrail);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"handrail"), new BlockItem(Handrail, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"whiteroundcarpet"), WhiteRoundCarpet);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"whiteroundcarpet"), new BlockItem(WhiteRoundCarpet, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"stairswall"), StairsWall);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"stairswall"), new BlockItem(StairsWall, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"fridge"), Fridge);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"fridge"), new BlockItem(Fridge, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"stair_steps_handrail_wall_l"), StairStepsHandrailWallL);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"stair_steps_handrail_wall_l"), new BlockItem(StairStepsHandrailWallL, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"wardrobe"), Wardrobe);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"wardrobe"), new BlockItem(Wardrobe, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"chair1"), Chair1);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"chair1"), new BlockItem(Chair1, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"curtain"), Curtain);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"curtain"), new BlockItem(Curtain, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"notebook"), Notebook);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"notebook"), new BlockItem(Notebook, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"stairstepshandrailwallr"), StairStepsHandrailWallR);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"stairstepshandrailwallr"), new BlockItem(StairStepsHandrailWallR, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"stairswallr"), StairsWallR);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"stairswallr"), new BlockItem(StairsWallR, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"table1"), Table1);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"table1"), new BlockItem(Table1, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"table2"), Table2);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"table2"), new BlockItem(Table2, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"stairswalll"), StairsWallL);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"stairswalll"), new BlockItem(StairsWallL, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"stairs"), Stairs);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"stairs"), new BlockItem(Stairs, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"centertable"), CenterTable);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"centertable"), new BlockItem(CenterTable, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"woodstructure"), WoodStructure);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"woodstructure"), new BlockItem(WoodStructure, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"handrailwall"), HandrailWall);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"handrailwall"), new BlockItem(HandrailWall, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"blackroundcarpet"), BlackRoundCarpet);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"blackroundcarpet"), new BlockItem(BlackRoundCarpet, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"whiteroundtable"), WhiteRoundTable);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"whiteroundtable"), new BlockItem(WhiteRoundTable, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"stairstepsmid"), StairStepsMid);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"stairstepsmid"), new BlockItem(StairStepsMid, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
        Registry.register(Registry.BLOCK, new Identifier(MOD_ID,"ceilinglamp"), CeilingLamp);
        Registry.register(Registry.ITEM, new Identifier(MOD_ID,"ceilinglamp"), new BlockItem(CeilingLamp, new Item.Settings().group(ModernArchMain.ModernArchGroup)));
    }
}
